jwt_secret: secret

app_name: auth_service
environment: dev
log_level: debug

host: postgres_db_compose
port: 5432
username: root
password: root
dbname: postgres

redis:
  address: redis://redis_db_compose:6379/1
  timeout: 3
  pool_size: 100

token_cache:
  access_token_timeout: 15
  refresh_token_timeout: 1440
